apiVersion: v1
kind: Service
metadata:
  name: samed-guener-portfolio-service
  labels:
    app: samed-guener-portfolio-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: samed-guener-portfolio
  