name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.58.3'
    - name: Build website
      run: hugo --minify
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
    - name: Upload files to samedguener.com
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: -m cp -r public/* gs://samedguener.com/
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
    - name: Upload files to samedguener.de
      uses: docker://gcr.io/cloud-builders/gsutil
      with:
        args: -m cp -r public/* gs://samedguener.de/
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}