name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/aws@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 sync . s3://samedguener.com/
